/* 
 * File:   ECU_LAYER_INIT.c
 * Author: amr09
 *
 * Created on July 31, 2024, 3:05 PM
 */

#include "ECU_LAYER_INIT.h"
/*
interrupt_RBx_t rb4 = {
    .EXTERNAL_INTERRUBT_HANDLER_HIGH = rb0_app_isr,
    .EXTERNAL_INTERRUBT_HANDLER_LOW = rb1_app_isr,
    .PRIORITY = INTERRUPT_HIGH_PRIORITY,
    .MCU_PIN = {
        .PORT = PORTB_INDEX,
        .PIN = PIN4,
        .DIRECTION = GPIO_DIRECTION_INPUT,
        .LOGIC = GPIO_LOW
    }
};
 interrupt_INTx_t int0={
    .EXTERNAL_INTERRUBT_HANDLER = int0_app_isr,
    .EDGE = RISING_EDGE,
    .PRIORITY = INTERRUPT_HIGH_PRIORITY,
    .SOURCE = EXT_INT0,
    .MCU_PIN = {
        .PORT = PORTB_INDEX,
        .PIN = PIN0,
        .DIRECTION = GPIO_DIRECTION_INPUT,
        .LOGIC = GPIO_LOW
    }
};
 *
 * 
 * 
//heart shape
uint8 customChar3[] = {
  0x00,
  0x0A,
  0x1F,
  0x1F,
  0x0E,
  0x04,
  0x00,
  0x00
};

_7_seg_t seg1 = {
    ._7_SEG_PINS[0].PORT = PORTC_INDEX,
    ._7_SEG_PINS[0].PIN = PIN0,
    ._7_SEG_PINS[0].LOGIC = GPIO_LOW,
    ._7_SEG_PINS[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    ._7_SEG_PINS[1].PORT = PORTC_INDEX,
    ._7_SEG_PINS[1].PIN = PIN1,
    ._7_SEG_PINS[1].LOGIC = GPIO_LOW,
    ._7_SEG_PINS[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    ._7_SEG_PINS[2].PORT = PORTC_INDEX,
    ._7_SEG_PINS[2].PIN = PIN2,
    ._7_SEG_PINS[2].LOGIC = GPIO_LOW,
    ._7_SEG_PINS[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    ._7_SEG_PINS[3].PORT = PORTC_INDEX,
    ._7_SEG_PINS[3].PIN = PIN3,
    ._7_SEG_PINS[3].LOGIC = GPIO_LOW,
    ._7_SEG_PINS[3].DIRECTION = GPIO_DIRECTION_OUTPUT
};

pin_config_t seg1_enable = {
    .PORT = PORTD_INDEX,
    .PIN = PIN0,
    .LOGIC = GPIO_LOW,
    .DIRECTION = GPIO_DIRECTION_OUTPUT
};

pin_config_t seg2_enable = {
    .PORT = PORTD_INDEX,
    .PIN = PIN1,
    .LOGIC = GPIO_LOW,
    .DIRECTION = GPIO_DIRECTION_OUTPUT
};

keypad_t key1 = {
    .KEYPAD_ROW_PINS[0].PORT = PORTB_INDEX,
    .KEYPAD_ROW_PINS[0].PIN = PIN0,
    .KEYPAD_ROW_PINS[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .KEYPAD_ROW_PINS[0].LOGIC = GPIO_LOW,
    .KEYPAD_ROW_PINS[1].PORT = PORTB_INDEX,
    .KEYPAD_ROW_PINS[1].PIN = PIN1,
    .KEYPAD_ROW_PINS[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .KEYPAD_ROW_PINS[1].LOGIC = GPIO_LOW,
    .KEYPAD_ROW_PINS[2].PORT = PORTB_INDEX,
    .KEYPAD_ROW_PINS[2].PIN = PIN2,
    .KEYPAD_ROW_PINS[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .KEYPAD_ROW_PINS[2].LOGIC = GPIO_LOW,
    .KEYPAD_ROW_PINS[3].PORT = PORTB_INDEX,
    .KEYPAD_ROW_PINS[3].PIN = PIN3,
    .KEYPAD_ROW_PINS[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .KEYPAD_ROW_PINS[3].LOGIC = GPIO_LOW,
    
    .KEYPAD_COLUMN_PINS[0].PORT = PORTB_INDEX,
    .KEYPAD_COLUMN_PINS[0].PIN = PIN4,
    .KEYPAD_COLUMN_PINS[0].DIRECTION = GPIO_DIRECTION_INPUT,
    .KEYPAD_COLUMN_PINS[0].LOGIC = GPIO_LOW,
    .KEYPAD_COLUMN_PINS[1].PORT = PORTB_INDEX,
    .KEYPAD_COLUMN_PINS[1].PIN = PIN5,
    .KEYPAD_COLUMN_PINS[1].DIRECTION = GPIO_DIRECTION_INPUT,
    .KEYPAD_COLUMN_PINS[1].LOGIC = GPIO_LOW,
    .KEYPAD_COLUMN_PINS[2].PORT = PORTB_INDEX,
    .KEYPAD_COLUMN_PINS[2].PIN = PIN6,
    .KEYPAD_COLUMN_PINS[2].DIRECTION = GPIO_DIRECTION_INPUT,
    .KEYPAD_COLUMN_PINS[2].LOGIC = GPIO_LOW,
    .KEYPAD_COLUMN_PINS[3].PORT = PORTB_INDEX,
    .KEYPAD_COLUMN_PINS[3].PIN = PIN7,
    .KEYPAD_COLUMN_PINS[3].DIRECTION = GPIO_DIRECTION_INPUT,
    .KEYPAD_COLUMN_PINS[3].LOGIC = GPIO_LOW,
};

char_lcd_4bit_t lcd1 = {
    .LCD_RS.PORT = PORTC_INDEX,
    .LCD_RS.PIN = PIN6,
    .LCD_RS.DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_RS.LOGIC = GPIO_LOW,
    
    .LCD_EN.PORT = PORTC_INDEX,
    .LCD_EN.PIN = PIN7,
    .LCD_EN.DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_EN.LOGIC = GPIO_LOW,
    
    .LCD_DATA[0].PORT = PORTD_INDEX,
    .LCD_DATA[0].PIN = PIN2,
    .LCD_DATA[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[0].LOGIC = GPIO_LOW,
    .LCD_DATA[1].PORT = PORTD_INDEX,
    .LCD_DATA[1].PIN = PIN3,
    .LCD_DATA[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[1].LOGIC = GPIO_LOW,
    .LCD_DATA[2].PORT = PORTD_INDEX,
    .LCD_DATA[2].PIN = PIN4,
    .LCD_DATA[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[2].LOGIC = GPIO_LOW,
    .LCD_DATA[3].PORT = PORTD_INDEX,
    .LCD_DATA[3].PIN = PIN5,
    .LCD_DATA[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[3].LOGIC = GPIO_LOW,

};

char_lcd_8bit_t lcd2 = {
    .LCD_RS.PORT = PORTD_INDEX,
    .LCD_RS.PIN = PIN2,
    .LCD_RS.DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_RS.LOGIC = GPIO_LOW,
    
    .LCD_EN.PORT = PORTD_INDEX,
    .LCD_EN.PIN = PIN1,
    .LCD_EN.DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_EN.LOGIC = GPIO_LOW,
    
    .LCD_DATA[0].PORT = PORTC_INDEX,
    .LCD_DATA[0].PIN = PIN0,
    .LCD_DATA[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[0].LOGIC = GPIO_LOW,
    .LCD_DATA[1].PORT = PORTC_INDEX,
    .LCD_DATA[1].PIN = PIN1,
    .LCD_DATA[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[1].LOGIC = GPIO_LOW,
    .LCD_DATA[2].PORT = PORTC_INDEX,
    .LCD_DATA[2].PIN = PIN2,
    .LCD_DATA[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[2].LOGIC = GPIO_LOW,
    .LCD_DATA[3].PORT = PORTC_INDEX,
    .LCD_DATA[3].PIN = PIN3,
    .LCD_DATA[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[3].LOGIC = GPIO_LOW,
    .LCD_DATA[4].PORT = PORTC_INDEX,
    .LCD_DATA[4].PIN = PIN4,
    .LCD_DATA[4].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[4].LOGIC = GPIO_LOW,
    .LCD_DATA[5].PORT = PORTC_INDEX,
    .LCD_DATA[5].PIN = PIN5,
    .LCD_DATA[5].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[5].LOGIC = GPIO_LOW,
    .LCD_DATA[6].PORT = PORTC_INDEX,
    .LCD_DATA[6].PIN = PIN6,
    .LCD_DATA[6].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[6].LOGIC = GPIO_LOW,
    .LCD_DATA[7].PORT = PORTC_INDEX,
    .LCD_DATA[7].PIN = PIN7,
    .LCD_DATA[7].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LCD_DATA[7].LOGIC = GPIO_LOW,

};

led_matrix_t led_matrix1 = {
    .LED_MATRIX_ROW_PINS[0].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[0].PIN = PIN0,
    .LED_MATRIX_ROW_PINS[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[0].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[1].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[1].PIN = PIN1,
    .LED_MATRIX_ROW_PINS[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[1].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[2].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[2].PIN = PIN2,
    .LED_MATRIX_ROW_PINS[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[2].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[3].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[3].PIN = PIN3,
    .LED_MATRIX_ROW_PINS[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[3].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[4].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[4].PIN = PIN4,
    .LED_MATRIX_ROW_PINS[4].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[4].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[5].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[5].PIN = PIN5,
    .LED_MATRIX_ROW_PINS[5].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[5].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[6].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[6].PIN = PIN6,
    .LED_MATRIX_ROW_PINS[6].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[6].LOGIC = GPIO_LOW,
    .LED_MATRIX_ROW_PINS[7].PORT = PORTD_INDEX,
    .LED_MATRIX_ROW_PINS[7].PIN = PIN7,
    .LED_MATRIX_ROW_PINS[7].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_ROW_PINS[7].LOGIC = GPIO_LOW,
    
    .LED_MATRIX_COLUMN_PINS[0].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[0].PIN = PIN0,
    .LED_MATRIX_COLUMN_PINS[0].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[0].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[1].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[1].PIN = PIN1,
    .LED_MATRIX_COLUMN_PINS[1].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[1].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[2].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[2].PIN = PIN2,
    .LED_MATRIX_COLUMN_PINS[2].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[2].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[3].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[3].PIN = PIN3,
    .LED_MATRIX_COLUMN_PINS[3].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[3].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[4].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[4].PIN = PIN4,
    .LED_MATRIX_COLUMN_PINS[4].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[4].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[5].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[5].PIN = PIN5,
    .LED_MATRIX_COLUMN_PINS[5].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[5].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[6].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[6].PIN = PIN6,
    .LED_MATRIX_COLUMN_PINS[6].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[6].LOGIC = GPIO_LOW,
    .LED_MATRIX_COLUMN_PINS[7].PORT = PORTC_INDEX,
    .LED_MATRIX_COLUMN_PINS[7].PIN = PIN7,
    .LED_MATRIX_COLUMN_PINS[7].DIRECTION = GPIO_DIRECTION_OUTPUT,
    .LED_MATRIX_COLUMN_PINS[7].LOGIC = GPIO_LOW,
};

*/
std_ReturnType ret = E_NOT_OK;

void ECU_INIT(){
    //ret = LED_MATRIX_INIT(&led_matrix1);
    /*
    ret = LCD_4BIT_INIT(&lcd1);
    ret = _7_SEG_INIT(&seg1);
    ret = KEYPAD_INIT(&key1);
    ret = GPIO_PIN_INITIALIZE(&seg1_enable);
    ret = GPIO_PIN_INITIALIZE(&seg2_enable);
    ret = LCD_8BIT_INIT(&lcd2);
    ret = INTERRUPT_INTx_INIT(&int0);
     */
}
